source 'https://rubygems.org'

gem 'rack'
gem 'rake'
gem 'rspec', '~> 3.5'
gem 'pry'
gem 'activesupport', '~> 5.0'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'awesome_print'
gem 'standalone_migrations'
gem 'hanami-router'
gem 'hanami-controller'
gem 'rack-console'
gem 'trailblazer-cells'
gem 'cells'
gem 'cells-haml'
